name: ASTERRA CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: |
          pip install flake8
          flake8 app/src

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: |
          cd app
          pip install -r requirements.txt
          pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker build -t asterra-geo-worker:${{ github.sha }} .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          echo "Logging to ECR using secrets"
          echo "Pushing image"
          echo "Updating ECS task definition"
